app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/
Route::group(['middleware' => 'web'], function () {

    /** Scaffold Auth Routes **/
    Route::auth();
    /** End Of Scaffold Auth Routes **/

    /** Place to enter a code. **/
    Route::get('/download', 'HomeController@index')->name('home');

    Route::post('/download/codeCheck', 'HomeController@codeCheck')->name('codecheck');
    /** End of Place to enter a code. **/

    /** Upload and Zip Files . **/
    Route::get('upload', 'FileEntryController@index')->name('fileentry');

    Route::get('upload/get/{filename}', [
        'as' => 'getentry', 'uses' => 'FileEntryController@get']);

    Route::post('upload/add',[
        'as' => 'addentry', 'uses' => 'FileEntryController@add']);

    Route::get('upload/download{filename}',[
        'as' => 'downloadentry', 'uses' => 'FileEntryController@download']);

    Route::post('upload/zip',[
        'as' => 'multipleselect', 'uses' => 'FileEntryController@zipFiles']);

    Route::post('upload/zipName',[
        'as' => 'zipname', 'uses' => 'FileEntryController@archiveName']);

    Route::get('upload/archives',[
        'as' => 'archives', 'uses' => 'FileEntryController@archiveList']);
    /** End Of Upload and Zip Files **/

    /** Invoice Routes**/
    Route::get('invoice/export/{id}', 'InvoiceController@export')->name('invoice.export');

    Route::resource('invoice', 'InvoiceController');
    /** End Of Invoice Routes**/

});

app/Invoice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{
    protected $table = 'invoices';
    protected $fillable = [
        'description',
//        'notes',
        'institution_name',
        'intermediary_name',
        'intermediary_bank',
        'intermediary_location',
        'institution_bank',
        'institution_street',
        'institution_city',
        'institution_country',
        'beneficiary_number',
        'beneficiary_company',
        'beneficiary_address',
        'beneficiary_city',
        'company_name',
        'company_address',
        'company_zip',
        'company_city',
        'company_country',
        'cost',
        'amount_payable',
        'total',
        'subtotal',
        'tax',
        'project'
    ];

    public function users()
    { // looking for groups user has.
        //('manyToMany Model', 'PivotModel','thisModelPivotId','local id of model you searching')
//        return $this->hasManyThrough('App\User','App\InvoiceUser','invoice_id', 'id');
        return $this->belongsToMany('App\User');

    }
}

app/Http/Controllers/InvoiceController.php
<?php

namespace App\Http\Controllers;

use App\InvoiceUser;
use App\User;
use Auth;
use Illuminate\Http\Request;
use App\Invoice;
use Barryvdh\Snappy\Facades\SnappyPdf as PDF;


class InvoiceController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $invoices = Invoice::with('users')->get();
        return view('invoice.list', compact('invoices'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return view('invoice.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request     *
     */
    public function store(Request $request)
    {
//        $request->except(['created_at', 'updated_at']);
        $invoice = new Invoice();

        $invoice->project = $request->input('project');
        $invoice->description = $request->input('description');
//        $invoice->notes = $request->input('notes');
        $invoice->intermediary_name = $request->input('intermediary_name');
        $invoice->intermediary_bank = $request->input('intermediary_bank');
        $invoice->intermediary_location = $request->input('intermediary_location');
//        $invoice->institution_name = $request->input('institution_name');
//        $invoice->institution_bank = $request->input('institution_bank');
//        $invoice->institution_street = $request->input('institution_street');
//        $invoice->institution_city = $request->input('institution_city');
//        $invoice->institution_country = $request->input('institution_country');
//        $invoice->beneficiary_number = $request->input('beneficiary_number');
//        $invoice->beneficiary_company = $request->input('beneficiary_company');
//        $invoice->beneficiary_address = $request->input('beneficiary_address');
//        $invoice->beneficiary_city = $request->input('beneficiary_city');
//        $invoice->company_name = $request->input('beneficiary_company');
//        $invoice->company_address = $request->input('beneficiary_address');
//        $invoice->company_zip = $request->input('beneficiary_zip');
//        $invoice->company_city = $request->input('beneficiary_city');
//        $invoice->company_country = $request->input('beneficiary_country');
        $invoice->amount_payable = $request->input('amount_payable');
        $invoice->cost = $request->input('cost');
        $invoice->total = $request->input('total');
        $invoice->subtotal = $request->input('subtotal');
        $invoice->tax = $request->input('tax');
        $invoice->save();

        $pivot = new InvoiceUser;
        $pivot->invoice_id =  $invoice->id;
        $pivot->user_id =  \Auth::user()->id;
        $pivot->save();
        return redirect()->route('invoice.export',$invoice->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $invoice = \Auth::user()->invoices()->first();
        return view('invoice.user_invoice', compact('invoice'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * @param $id
     *
     * @return mixed
     */
    public function export($id)
    { // daj mu id u argumentu a dole u invoice da nadje po tom id-u pdf......
//        $invoice =  \Auth::user()->invoices()->first();
//        $html = (string) view('invoice.user_invoice');
//        dd($html);
        // for download (in public folder):
//        $data = [];
//        $pdf = PDF::loadView('invoice.test', $data);
//        $pdf->save('invoice.pdf');
//        return \Response::download('invoice.pdf');

        // for stream:

//        $invoice =  \Auth::user()->invoices()->first();
        $invoice =  Invoice::find($id);
        $pdf = PDF::loadView('invoice.user_invoice', array('invoice' => $invoice));
        return $pdf->stream('invoice.pdf');

//        \Excel::create('Pedeef', function($excel) {
//            $excel->sheet('pdfff', function($sheet) {
//                $sheet->setAutoSize(true);
//                $sheet->loadView('invoice.test');
//            });
//        })->export('pdf');


    }


}

resources/views/invoice/[old] create.blade.php
@extends('invoice.layout')
@section('content')
        <!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Sample Invoice</title>
    <link rel="stylesheet" href="css/bootstrap.css">
    <style>
        @import url(http://fonts.googleapis.com/css?family=Bree+Serif);
        body, h1, h2, h3, h4, h5, h6{
            font-family: 'Bree Serif', serif;
        }
    </style>
</head>

<body>
<div class="container">
    <div class="row">
        <div class="col-ls-12 logo">
            <div class="logo-img">
                <img src="{{ asset('/images/logo.png') }}">
            </div>
        </div>
    </div>
    <form action="{{ route('invoice.store') }}" method="POST">
        {{ csrf_field() }}
        <div class="row">
            <div class="col-xs-6">
                <h1>INVOICE</h1>
                <h1><small>Invoice #001</small></h1>
            </div>
            <div class="col-xs-6 text-right">
                <h1>{{ date('dS F o') }}</h1>
                <h1>Project: <input name="project" type="text" placeholder="Enter project name"></h1></h1>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-5">
                <div class="panel panel-default">
                    <div class="panel-heading from-to">
                        <h3>FROM:</h3>
                    </div>
                    <div class="panel-body">
                        <p>Chordate D.O.O</p>
                        <p> Beograd - Stari Grad,</p>
                        <p> Tadeusa Koscuska 12</p>
                        <p> Company #: 60430071</p>
                        <p> Tax #: 104716111 </p>
                        <p> oﬃce@chord.agency</p>
                    </div>
                </div>
            </div>
            <div class="col-xs-5 col-xs-offset-2 text-right">
                <div class="panel panel-default">
                    <div class="panel-heading from-to">
                        <h3>TO:</h3>
                    </div>
                    <div class="panel-body">
                        <p> {{ \Auth::user()->company_name }} </p>
                        <p>{{ \Auth::user()->company_address }}</p>
                        <p>{{ \Auth::user()->company_city }} {{ \Auth::user()->company_zip }}</p>
                        <p>{{ \Auth::user()->company_country }}</p>
                    </div>
                </div>
            </div>
        </div>
        <!-- / end client details section -->
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>
                    <h4>DESCRIPTION</h4>
                </th>
                <th>
                    <h4>COST<select id="select">
                            <option value="1">(€)</option>
                            <option value="2">($)</option>
                            <option value="3">(£)</option>
                        </select></h4>
                </th>
                <th>
                    <h4>AMOUNT PAYABLE (%):</h4>
                </th>
                <th>
                    <h4>TOTAL:</h4>
                </th>
            </tr>
            </thead>
            <tbody class="plusrow">
            <tr>
                <td><h4><input name="description" type="text" placeholder="Describe it.."></h4></td>
                <td><h4><input name="cost" type="text" id="cost" placeholder="Cost"></h4></td>
                <td><h4><input name="amount_payable" type="text" id="percent" placeholder="Amount Payable"></h4></td>
                <td><h4><input name="total" type="text" id="subtotal" placeholder="Total"></h4></td>
            </tr>
            </tbody>
        </table>
        <div class="row text-right project-total">
            <div class="col-xs-2 col-xs-offset-8">

            </div>
            <div class="col-xs-2">
                <button type="button" class="btn btn-primary plusbtn"><span class="glyphicon glyphicon-plus"></span></button>
                <button type="button" class="btn btn-primary minusbtn"><span class="glyphicon glyphicon-minus"></span></button>
            </div>
        </div>
        <div class="row amount">
            <div class="col-xs-7">
                <div class="span7">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <h4>ACCOUNT DETAILS</h4>
                        </div>
                        <div class="panel-body">
                            <table class="table table-striped account">
                                <thead>
                                <tr>
                                    <td>INTERMEDIARY:</td>
                                    <td>INSTITUTION DETAILS:</td>
                                    <td>BENEFICIARY:</td>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td id="chifer"><input name="intermediary_name" value="BCITITMM" readonly></td>
                                    <td>DBDBRSBG</td>
                                    <td>RS35160005380001949022</td>
                                </tr>
                                <tr>
                                    <td id="bank"><input name="intermediary_bank" value="INTESA SANPAOLO SPA" readonly></td>
                                    <td>BANKA INTESA AD, BEOGRAD</td>
                                    <td>CHORDATE DOO BEOGRAD</td>
                                </tr>
                                <tr>
                                    <td id="city"><input name="intermediary_location" value="MILANO, ITALY" size="26" readonly></td>
                                    <td>MILENTIJA POPOVICA 7B</td>
                                    <td>TADEUSA KOSCUSKA 12</td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td>BEOGRAD, REPUBLIKA SRBIJA</td>
                                    <td>BEOGRAD - STARI GRAD</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-5">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h4>AMOUNT DUE</h4>
                    </div>
                    <div class="panel-body">
                        <table class="table table-striped account">
                            <thead>
                            <tr>
                                <td>Subtotal</td>
                                <td><input id="Subtotal" name="subtotal" readonly></td>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>Tax</td>
                                <td><input id="tax" type="text" name="tax"></td>
                            </tr>
                            <tr>
                                <td></td>
                                <td></td>
                            </tr>

                            <tr>
                                <td>TOTAL</td>
                                <td><input id="total" type="text" name="total" readonly></td>
                            </tr>
                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-7">
                <div class="span7">
                    <div class="panel panel-info notes">
                        <div class="notes">
                            <h4>NOTES</h4>
                        </div>
                        <div class="panel-body">
                            <table class="table table-striped">
                                <thead>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-5">
                <div class="signature">
                    <div class="panel-heading">
                        <h4></h4>
                    </div>
                    <div class="panel-body">
                        <table class="table table-striped">
                            <thead>
                            <tr>

                            </tr>
                            </thead>
                            <tbody>
                            <tr>

                            </tr>
                            <tr>

                            </tr>

                            <tr>

                                <td style="border-top: thin solid;"></td>
                            </tr>
                            </tbody>
                        </table>
                        <div style="text-align: center;"><h6>JACK GORDON HARRIS - MANAGING DIRECTOR</h6></div>
                        <input type="submit" class="btn btn-info invoice" value="Submit Button">
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
</body>
</html>
@endsection

resources/views/invoice/create.blade.php
@extends('invoice.layout')
@section('content')
    <div class="bs-example">
        <form action="{{ route('invoice.store') }}" method="POST">

            <div class="form-group">
                <h4>TO: <select id="client">
                        <option value="1">CLIENT #X</option>
                        <option value="2">CLIENT #X</option>
                        <option value="3">CLIENT #X</option>
                    </select></h4>
            </div>

            <div class="form-group">
                <h4>COST: <select id="select">
                        <option value="1">(€)</option>
                        <option value="2">($)</option>
                        <option value="3">(£)</option>
                    </select></h4>
            </div>

            <div class="form-group">
                <label for="project">Project</label>
                <input type="text" class="form-control" id="project" placeholder="Project">
            </div>

            <div class="form-group">
                <label for="client">P/O Number</label>
                <input type="text" class="form-control" id="P/O" placeholder="P/O">
            </div>

            <div class="form-group">
                <table responsive-table>
                    <tbody class="plusrow">
                    <tr>
                        <td><input name="description" type="text" class="form-control" placeholder="Describe it.."></td>
                        <td><input name="cost" type="text" id="cost" class="form-control" placeholder="Cost"></td>
                        <td><input name="amount_payable" type="text" id="percent" class="form-control" placeholder="Amount Payable"></td>
                        <td><input name="total" type="text" id="subtotal" class="form-control" placeholder="SubTotal"></td>
                    </tr>
                    </tbody>
                </table>
            </div>

            <div class="form-group">
                <label for="tax">Tax</label>
                <input id="tax" class="form-control" placeholder="Tax" type="text" name="tax">
                <label for="total">TOTAL</label>
                <input id="total" class="form-control" placeholder="Total" type="text" name="total">
            </div>
            <div class="row text-right project-total">
                <div class="col-xs-2 col-xs-offset-8">
                </div>
                <div class="col-xs-2">
                    <button type="button" class="btn btn-primary plusbtn"><span class="glyphicon glyphicon-plus"></span>
                    </button>
                    <button type="button" class="btn btn-primary minusbtn"><span
                                class="glyphicon glyphicon-minus"></span></button>
                </div>
            </div>
            <div class="form-group">
                <label for="comment">Notes:</label>
                <textarea class="form-control" rows="5" id="comment"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

@endsection

resources/views/invoice/layout.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Invoice</title>

    <!-- Bootstrap Core CSS -->
    {{--<link href="{{asset('css/bootstrap.min.css')}}" rel="stylesheet">--}}
    {{--<link href="{{asset('css/bootstrap.css')}}" rel="stylesheet">--}}

    <!-- Custom CSS -->
    <link href="{{asset('css/admin.css')}}" rel="stylesheet">
    {{--<link href="{{asset('css/invoice.css')}}" rel="stylesheet">--}}
    <link href="{{asset('css/upload.css')}}" rel="stylesheet">
    <link href="{{asset('css/test.css')}}" rel="stylesheet">
    {{--<link href="{{asset('css/downloads.css')}}" rel="stylesheet">--}}
    <link rel="stylesheet" href="{{ public_path().'/css/test.css' }}">


    <style type="text/css">
        .header{
            background-color: #843534;
            height: auto;
            padding: 10px; !important;
        }

        .header-text p{
            text-align: right;
            padding: 0;
            margin: 0;
            color: #fff;
        }

        .container2{
            border: 1px solid #8f9497; !important;
        }

        .htext{
            color: #675F5A;
        }

        .down-header h3{
            padding: 0;
            margin: 0;
            padding-bottom: 5px;
        }

        .second-header{
            margin-top: 20px;
            margin-bottom: 10px;
            padding-left: 15px; !important;
            padding-right: 15px; !important;
        }

        .from{
            border: 2px solid #856C66;
            border-radius: 5px;
            padding: 2px; !important;
        }

        .account{
            border: 2px solid #856C66;
            border-radius: 5px;
            padding: 0; !important;
        }

        .to{
            border: 2px solid #856C66;
            border-radius: 5px;
            padding: 2px; !important;
        }

        .from-header{
            background-color: #856C66;
            border-top-left-radius: 5px; !important;
            border-top-right-radius: 5px; !important;
            margin-bottom: 5px; !important;

        }
        .table{
            margin-bottom: 0px; !important;
        }
        .from-header h4{
            color: #fff;
        }

        .from-text > p{
            background-color: #EEEDED; !important;
            padding: 0 0 0 5px; !important;
            margin: 0;
            margin-bottom: 3px;
            color: #807874; !important;
        }

        .description{
            background-color: #C47B5D;
            border-top-left-radius: 5px; !important;
            border-top-right-radius: 5px; !important;
            margin-bottom: 5px; !important;
        }

        .description h4{
            color: #fff;
        }

        .description2{
            background-color: #E6BE73;
            border-top-left-radius: 2px; !important;
            border-top-right-radius: 2px; !important;
            margin-bottom: 5px; !important;
        }

        .description2 h4{
            color: #fff;
        }
        input.btn.btn-info.invoice {
            float: right;
            margin: 50px 100px;
        }
    </style>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <script src="http://s.codepen.io/assets/libs/modernizr.js" type="text/javascript"></script>
    <![endif]-->



</head>

<body>
@yield('content')

<!-- /.container -->

<!-- jQuery -->
<script src="{{asset('js/jquery.js')}}"></script>
<script src="{{asset('js/jquery.min.js')}}"></script>
<script src="{{asset('js/calculations.js')}}"></script>
<script src="{{asset('js/tableplus.js')}}"></script>
<script src="{{asset('js/upload.js')}}"></script>
<script src="{{asset('js/zip.js')}}"></script>
<script src="{{asset('js/accounts_change.js')}}"></script>


<!-- Bootstrap Core JavaScript -->
<script src="{{asset('js/bootstrap.min.js')}}"></script>


</body>

</html>

resources/views/invoice/list.blade.php
@extends('invoice.admin.admin')

@section('sidebar')
    <div class="row second-header">
        <div class="col-lg-12 ">
            <div class="col-lg-12 from">
                <div class="col-lg-12 text-left description">
                    {{--<h4>From:</h4>--}}
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <td><h4>Invoice #</h4></td>
                            <td><h4>Client Name</h4></td>
                            <td><h4>Project</h4></td>
                            <td><h4>Amount</h4></td>
                        </tr>
                        </thead>
                    </table>
                </div>
                <div class="col-lg-12">
                    <table class="table table-striped">
                        <thead>
                        @foreach ($invoices as $invoice)
                            @foreach ($invoice->users as $users)
                                <tr>
                                    <td>{{$invoice->id}}</td>
                                    <td>{{$users->name}}</td>
                                    <td>{{$invoice->description}}</td>
                                    <td>{{$invoice->total}}</td>
                                </tr>
                            @endforeach
                        @endforeach
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
@stop