app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/
Route::group(['middleware' => 'web'], function () {

    /** Scaffold Auth Routes **/
    Route::auth();
    /** End Of Scaffold Auth Routes **/

    /** Place to enter a code. **/
    Route::get('/download', 'HomeController@index')->name('home');

    Route::post('/download/codeCheck', 'HomeController@codeCheck')->name('codecheck');
    /** End of Place to enter a code. **/

    /** Upload and Zip Files . **/
    Route::get('upload', 'FileEntryController@index')->name('fileentry');

    Route::get('upload/get/{filename}', [
        'as' => 'getentry', 'uses' => 'FileEntryController@get']);

    Route::post('upload/add',[
        'as' => 'addentry', 'uses' => 'FileEntryController@add']);

    Route::get('upload/download{filename}',[
        'as' => 'downloadentry', 'uses' => 'FileEntryController@download']);

    Route::post('upload/zip',[
        'as' => 'multipleselect', 'uses' => 'FileEntryController@zipFiles']);

    Route::post('upload/zipName',[
        'as' => 'zipname', 'uses' => 'FileEntryController@archiveName']);

    Route::get('upload/archives',[
        'as' => 'archives', 'uses' => 'FileEntryController@archiveList']);
    /** End Of Upload and Zip Files **/

    /** Invoice Routes**/
    Route::get('invoice/export/{id}', 'InvoiceController@export')->name('invoice.export');

    Route::resource('invoice', 'InvoiceController');
    /** End Of Invoice Routes**/

});

app/Invoice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{
    protected $table = 'invoices';
    protected $fillable = [
        'description',
//        'notes',
        'institution_name',
        'intermediary_name',
        'intermediary_bank',
        'intermediary_location',
        'institution_bank',
        'institution_street',
        'institution_city',
        'institution_country',
        'beneficiary_number',
        'beneficiary_company',
        'beneficiary_address',
        'beneficiary_city',
        'company_name',
        'company_address',
        'company_zip',
        'company_city',
        'company_country',
        'cost',
        'amount_payable',
        'total',
        'subtotal',
        'tax',
        'project'
    ];

    public function users()
    { // looking for groups user has.
        //('manyToMany Model', 'PivotModel','thisModelPivotId','local id of model you searching')
//        return $this->hasManyThrough('App\User','App\InvoiceUser','invoice_id', 'id');
        return $this->belongsToMany('App\User');

    }
}

app/Http/Controllers/InvoiceController.php
<?php

namespace App\Http\Controllers;

use App\InvoiceUser;
use App\User;
use Auth;
use Illuminate\Http\Request;
use App\Invoice;
use Barryvdh\Snappy\Facades\SnappyPdf as PDF;


class InvoiceController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $invoices = Invoice::with('users')->get();
        return view('invoice.list', compact('invoices'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return view('invoice.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request     *
     */
    public function store(Request $request)
    {
//        $request->except(['created_at', 'updated_at']);
        $invoice = new Invoice();

        $invoice->project = $request->input('project');
        $invoice->description = $request->input('description');
//        $invoice->notes = $request->input('notes');
        $invoice->intermediary_name = $request->input('intermediary_name');
        $invoice->intermediary_bank = $request->input('intermediary_bank');
        $invoice->intermediary_location = $request->input('intermediary_location');
//        $invoice->institution_name = $request->input('institution_name');
//        $invoice->institution_bank = $request->input('institution_bank');
//        $invoice->institution_street = $request->input('institution_street');
//        $invoice->institution_city = $request->input('institution_city');
//        $invoice->institution_country = $request->input('institution_country');
//        $invoice->beneficiary_number = $request->input('beneficiary_number');
//        $invoice->beneficiary_company = $request->input('beneficiary_company');
//        $invoice->beneficiary_address = $request->input('beneficiary_address');
//        $invoice->beneficiary_city = $request->input('beneficiary_city');
//        $invoice->company_name = $request->input('beneficiary_company');
//        $invoice->company_address = $request->input('beneficiary_address');
//        $invoice->company_zip = $request->input('beneficiary_zip');
//        $invoice->company_city = $request->input('beneficiary_city');
//        $invoice->company_country = $request->input('beneficiary_country');
        $invoice->amount_payable = $request->input('amount_payable');
        $invoice->cost = $request->input('cost');
        $invoice->total = $request->input('total');
        $invoice->subtotal = $request->input('subtotal');
        $invoice->tax = $request->input('tax');
        $invoice->save();

        $pivot = new InvoiceUser;
        $pivot->invoice_id =  $invoice->id;
        $pivot->user_id =  \Auth::user()->id;
        $pivot->save();
        return redirect()->route('invoice.export',$invoice->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $invoice = \Auth::user()->invoices()->first();
        return view('invoice.user_invoice', compact('invoice'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    /**
     * @param $id
     *
     * @return mixed
     */
    public function export($id)
    { // daj mu id u argumentu a dole u invoice da nadje po tom id-u pdf......
//        $invoice =  \Auth::user()->invoices()->first();
//        $html = (string) view('invoice.user_invoice');
//        dd($html);
        // for download (in public folder):
//        $data = [];
//        $pdf = PDF::loadView('invoice.test', $data);
//        $pdf->save('invoice.pdf');
//        return \Response::download('invoice.pdf');

        // for stream:

//        $invoice =  \Auth::user()->invoices()->first();
        $invoice =  Invoice::find($id);
        $pdf = PDF::loadView('invoice.user_invoice', array('invoice' => $invoice));
        return $pdf->stream('invoice.pdf');

//        \Excel::create('Pedeef', function($excel) {
//            $excel->sheet('pdfff', function($sheet) {
//                $sheet->setAutoSize(true);
//                $sheet->loadView('invoice.test');
//            });
//        })->export('pdf');


    }


}

resources/views/invoice/admin/admin.blade.php
@extends('invoice.layout')

@section('content')
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle navbar-toggle-sidebar collapsed">
                    MENU
                </button>
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                    Administrator
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <form class="navbar-form navbar-left" method="GET" role="search">
                    <div class="form-group">
                        <input type="text" name="q" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default"><i class="glyphicon glyphicon-search"></i></button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="http://www.pingpong-labs.com" target="_blank">Visit Site</a></li>
                    <li class="dropdown ">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            Account
                            <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li class="dropdown-header">SETTINGS</li>
                            <li class=""><a href="#">Other Link</a></li>
                            <li class=""><a href="#">Other Link</a></li>
                            <li class=""><a href="#">Other Link</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>  	<div class="container-fluid main-container">
        <div class="col-md-2 sidebar">
            <div class="row">
                <!-- uncomment code for absolute positioning tweek see top comment in css -->
                <div class="absolute-wrapper"> </div>
                <!-- Menu -->
                <div class="side-menu">
                    <nav class="navbar navbar-default" role="navigation">
                        <!-- Main Menu -->
                        <div class="side-menu-container">
                            <ul class="nav navbar-nav">
                                <li class="active"><a href="{{route('invoice.index')}}"><span class="glyphicon glyphicon-dashboard"></span> Dashboard</a></li>
                                <li><a href="{{route('invoice.create')}}"><span class="glyphicon glyphicon-plane"></span> Add New Invoice</a></li>
                                <li><a href="{{route('fileentry')}}"><span class="glyphicon glyphicon-cloud"></span> Upload</a></li>
                                <li><a href="{{route('archives')}}"><span class="glyphicon glyphicon-user"></span> Archives</a></li>
                                <li><a href="{{route('home')}}"><span class="glyphicon glyphicon-signal"></span> Test</a></li>

                            </ul>
                        </div><!-- /.navbar-collapse -->
                    </nav>

                </div>
            </div>  		</div>
        <div class="col-md-10 content">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Dashboard
                </div>
                <div class="panel-body">
                    @yield('sidebar')
                </div>
            </div>
        </div>

    </div>
@stop